import { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en'); // 'en' or 'ar'

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
    };

    const translations = {
        en: {
            home: 'Home',
            contact: 'Contact',
            gifts: 'Gifts',
            login: 'sign in !',
            register: 'Register !',
            logo: "Hadiya",
            languageName: 'العربية',
            email: "example@gmail.com",
            lableEmail: "Email",
            lablePassword: "Password",
            lableUsername: "Username",
            password: "Password",
            username: "john doe",
            forgotPassword: "Forgot Password",
            loginButton: "Login With Your Account",
            registerButton: "Register Now!",
            or: "Or",
            haveAccount: "Already have an account?",
            loginLink: "Login",
            dontHaveAccount: "Don't have an account?",
            registerLink: "Register",
            login_title: "Create your Account and Share Your Gifts",
            login_subtitle: "Join our community and share your gifts with the world",
            herostion_title: " Send Love.",
            herostion_title_2: "Share Joy Instantly.",
            herostion_subtitle: "Create beautiful QR-powered gifts that deliver happiness, connection, and heartfelt moments — anytime, anywhere.",
            herosection_button: "🎁 Send a Gift Now",
            backToHome: "Back to Home",
            aboutUsTitle: "About Us",
            aboutUsSubTitle: "Connecting Hearts, One Gift at a Time.",
            aboutUsContent1: "We believe that distance should never be a barrier to expressing love. ShareGifts was born out of a desire to make digital gifting as personal and heartwarming as a physical embrace.",
            aboutUsContent1: "We believe that distance should never be a barrier to expressing love. ShareGifts was born out of a desire to make digital gifting as personal and heartwarming as a physical embrace.",
            aboutUsContent2: "Our mission is to help you create moments of joy that linger long after the screen is closed.",
            emotional_story: "Every gift tells a story. Every QR code carries a piece of your heart.",
            emotional_distance: "In a world of distance, bridge the gap with thoughtful gestures that truly matter.",
            emotional_connection: "Because the best gifts aren't just things - they're moments of connection and love.",
            intro_title: "How It Works",
            intro_subtitle: "Just three simple steps to create unforgettable moments and spread joy with your digital gifts.",
            intro_step1_title: "Create a Gift",
            intro_step1_desc: "Create a personalized gift with a heartfelt message and a unique QR code.",
            intro_step2_title: "Share the Gift",
            intro_step2_desc: "Send your QR gift instantly to your loved ones via link or social media.",
            intro_step3_title: "Enjoy the Moment",
            intro_step3_desc: "Watch their smile as they scan and receive your thoughtful surprise.",
            resetPassword: "Reset Password",
            resetPassword: "Reset Password",
            resetPasswordButton: "Reset Password",
            // Contacts
            getInTouch: "Get in",
            touch: "Touch",
            contactHeroText: "We'd love to hear from you. Whether you have a question about features, pricing, need a demo, or anything else, our team is ready to answer all your questions.",
            contactInfo: "Contact Information",
            ourLocation: "Our Location",
            emailUs: "Email Us",
            callUs: "Call Us",
            followUs: "Follow Us",
            sendMessage: "Send us a Message",
            fullName: "Full Name",
            emailAddress: "Email Address",
            subject: "Subject",
            message: "Message",
            sendBtn: "Send Message",
            locationText: "123 Innovation Drive, Tech City, TC 90210",
            messagePlaceholder: "Your message here...",
            subjectPlaceholder: "How can we help?",
            namePlaceholder: "John Doe",
            emailPlaceholder: "john@example.com",
            // Gifts
            createGiftTitle: "Create your",
            createGiftSubtitle: "Digital Gift",
            giftHeroText: "Make their moments special with simple steps",
            premiumGift: "Premium Gift",
            giftTo: "Gifted to",
            recipientName: "Recipient Name",
            senderName: "Recipient Name",
            recipientPhone: "Recipient Phone",
            giftValue: "Gift Value (SAR)",
            iban: " Recipient  (IBAN)",
            currency: "SAR",
            giftMessagePlaceholder: "Write a special message...",
            giftId: "ID: GIFT-8821-X",
            giftCreatedSuccess: "Gift created successfully!",
            processing: "Processing...",
            // Verify Email
            verifyEmailTitle: "Verify your email",
            sentCodeTo: "We've sent a code to",
            verifyBtn: "Verify Email",
            verifyBtnShort: "Verify",
            resendPrompt: "Didn't receive code?",
            resendBtn: "Resend",
            otpError: "Please enter specific 6-digit code",
            verifySuccess: "Email verified successfully!",
            verifyFail: "Verification failed",
            otpTitle: "OTP digit",
            // QR Code Page
            download: "Download Image",
            share: "Share",
            copyLink: "Copy Link",
            giftNumber: "Gift Number",
            expiryDate: "Expiry Date",
            linkCopied: "Link copied to clipboard!",
            shareNotSupported: "Sharing is not supported on this device.",
            // Gift Claim Page
            giftFrom: "Gift From",
            giftMessage: "Message",
            acceptGift: "Accept Gift",
            rejectGift: "Reject Gift",
            claimGiftTitle: "Claim Your Gift",
            claimGiftSubtitle: "Enter your details to receive the gift.",
            fullName: "Full Name",
            phone: "Phone Number",
            iban: "IBAN",
            submitClaim: "Submit Claim",
            giftClaimed: "Gift claimed successfully!",
            giftRejected: "Gift rejected.",
        },
        ar: {
            home: 'الرئيسية',
            contact: 'تواصل معنا',
            gifts: 'الهدايا',
            login: 'تسجيل الدخول',
            register: 'إنشاء حساب',
            logo: "Hadaya",
            languageName: 'English',
            email: "example@gmail.com",
            password: "Password",
            lableEmail: "Email",
            lablePassword: "Password",
            forgotPassword: "نسيت كلمة المرور",
            username: "اسم المستخدم",
            loginButton: "تسجيل الدخول",
            registerButton: "إنشاء حساب",
            or: "أو",
            haveAccount: "لديك حساب بالفعل؟",
            loginLink: "تسجيل الدخول",
            dontHaveAccount: "ليس لديك حساب؟",
            registerLink: "إنشاء حساب",
            login_title: "أنشئ حسابك وشارك هداياك",
            login_subtitle: "انضم إلى مجتمعنا وشارك هداياك مع العالم",
            herostion_title: "أرسل الحب.",
            herostion_title_2: "شارك الفرح فورًا.",
            herostion_subtitle: "انشيء هدايا صغيرة تحمل QR بطاقة تسمع الحب والاتصال والجزاءات المحيطة - في اي وقت وفي اي مكان.",
            herosection_button: "🎁 أرسل هدية الآن",
            herosection_button: "🎁 أرسل هدية الآن",
            backToHome: "العودة للرئيسية",
            aboutUsTitle: "من نحن",
            aboutUsSubTitle: "نصل القلوب، هدية تلو الأخرى.",
            aboutUsContent1: "نؤمن أن المسافات لا يجب أن تكون عائقاً أمام التعبير عن الحب. ولدت Hadiya من رغبة في جعل الإهداء الرقمي شخصياً ودافئاً كالعناق الحقيقي.",
            aboutUsContent1: "نؤمن أن المسافات لا يجب أن تكون عائقاً أمام التعبير عن الحب. ولدت Hadiya من رغبة في جعل الإهداء الرقمي شخصياً ودافئاً كالعناق الحقيقي.",
            aboutUsContent2: "مهمتنا هي مساعدتك على خلق لحظات من الفرح تبقى طويلاً بعد إغلاق الشاشة.",
            emotional_story: "كل هدية تروي قصة. كل رمز QR يحمل قطعة من قلبك.",
            emotional_distance: "في عالم تباعدت فيه المسافات، مد الجسور بلفتات مدروسة تعني الكثير.",
            emotional_connection: "لأن أفضل الهدايا ليست مجرد أشياء - إنها لحظات من التواصل والحب.",
            intro_title: "كيف يعمل",
            intro_subtitle: "ثلاث خطوات بسيطة لخلق لحظات لا تنسى ونشر الفرح بهداياك الرقمية.",
            intro_step1_title: "أنشئ هدية",
            intro_step1_desc: "أنشئ هدية مخصصة برسالة من القلب ورمز QR فريد.",
            intro_step2_title: "شارك الهدية",
            intro_step2_desc: "أرسل هديتك فوراً لأحبائك عبر رابط أو وسائل التواصل الاجتماعي.",
            intro_step3_title: "استمتع باللحظة",
            intro_step3_desc: "شاهد ابتسامتهم عندما يمسحون الرمز ويستقبلون مفاجأتك المدروسة.",
            resetPassword: "إعادة تعيين كلمة المرور",
            resetPassword: "إعادة تعيين كلمة المرور",
            resetPasswordButton: "إعادة تعيين كلمة المرور",
            // Contacts
            getInTouch: "تواصل",
            touch: "معنا",
            contactHeroText: "نحب أن نسمع منك. سواء كان لديك سؤال عن الميزات، الأسعار، تحتاج إلى عرض توضيحي، أو أي شيء آخر، فريقنا مستعد للإجابة على جميع أسئلتك.",
            contactInfo: "معلومات التواصل",
            ourLocation: "موقعنا",
            emailUs: "راسلنا",
            callUs: "اتصل بنا",
            followUs: "تابعنا",
            sendMessage: "أرسل لنا رسالة",
            fullName: "الاسم الكامل",
            emailAddress: "البريد الإلكتروني",
            subject: "الموضوع",
            message: "الرسالة",
            sendBtn: "إرسال الرسالة",
            locationText: "١٢٣ شارع الابتكار، مدينة التقنية، ٩٠٢١٠",
            messagePlaceholder: "رسالتك هنا...",
            subjectPlaceholder: "كيف يمكننا مساعدتك؟",
            namePlaceholder: "محمد أحمد",
            emailPlaceholder: "mohamed@example.com",
            // Gifts
            createGiftTitle: "أنشئ هديتك",
            createGiftSubtitle: "الرقمية",
            giftHeroText: "اجعل لحظاتهم مميزة بخطوات بسيطة",
            premiumGift: "هدية مميزة",
            giftTo: "مهداة إلى",
            recipientName: "اسم المستلم",
            recipientPhone: "رقم الهاتف",
            giftValue: "قيمة الهدية (ر.س)",
            iban: "رقم الحساب (IBAN)",
            currency: "ر.س",
            giftMessagePlaceholder: "اكتب رسالة خاصة...",
            giftId: "المعرف: GIFT-8821-X",
            giftCreatedSuccess: "تم إنشاء الهدية بنجاح!",
            processing: "جاري المعالجة...",
            // Verify Email
            verifyEmailTitle: "تحقق من بريدك الإلكتروني",
            sentCodeTo: "لقد أرسلنا رمزاً إلى",
            verifyBtn: "تحقق من البريد الإلكتروني",
            verifyBtnShort: "تحقق",
            resendPrompt: "لم تستلم الرمز؟",
            resendBtn: "إعادة إرسال",
            otpError: "الرجاء إدخال الرمز المكون من 6 أرقام",
            verifySuccess: "تم التحقق من البريد الإلكتروني بنجاح!",
            verifyFail: "فشل التحقق",
            otpTitle: "رقم الرمز",
            // QR Code Page
            download: "تحميل الصورة",
            share: "مشاركة",
            copyLink: "نسخ الرابط",
            giftNumber: "رقم الهدية",
            expiryDate: "تاريخ الانتهاء",
            linkCopied: "تم نسخ الرابط إلى الحافظة!",
            shareNotSupported: "المشاركة غير مدعومة على هذا الجهاز.",
            // Gift Claim Page
            giftFrom: "هدية من",
            giftMessage: "الرسالة",
            acceptGift: "قبول الهدية",
            rejectGift: "رفض الهدية",
            claimGiftTitle: "استلم هديتك",
            claimGiftSubtitle: "أدخل بياناتك لاستلام الهدية.",
            fullName: "الاسم الكامل",
            phone: "رقم الهاتف",
            submitClaim: "استلام الهدية",
            giftClaimed: "تم استلام الهدية بنجاح!",
            giftRejected: "تم رفض الهدية.",
        },
    };

    const t = (key) => translations[language][key] || key;
    const isRTL = language === 'ar';

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }
        }>
            <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : 'font-inter'}>
                {children}
            </div>
        </LanguageContext.Provider >
    );
};

export const useLanguage = () => useContext(LanguageContext);

